import {
  Wifi,
  Tv,
  Flame,
  DoorOpen,
  BedDouble,
  Wind,
  WashingMachine,
  Snowflake,
  Thermometer,
  ChefHat,
  Laptop,
  Coffee,
  Refrigerator,
  CookingPot,
  Utensils,
  Microwave,
  Car,
  BatteryCharging,
  Dumbbell,
  Waves,
  Landmark,
  Leaf,
  Croissant,
  Umbrella,
  Baby,
  Gamepad2,
  Shield,
  BriefcaseMedical,
  AlarmSmoke,
  ShowerHead,
  Bubbles,
  Hand,
  Bath,
  BookOpen,
  Dice6,
  Joystick,
  Clapperboard,
  Piano,
  Disc3,
  Accessibility,
  ArrowUpDown,
  Camera,
  Lock,
  Key,
  KeySquare,
  Bike,
  Sailboat,
  CableCar,
  LandPlot,
  Volleyball,
  Mountain,
  Martini,
  BrickWallFire,
  Shirt,
  Gift,
  SoapDispenserDroplet,
  BrushCleaning,
} from "lucide-react";
import { Card } from "./card";
import { useTranslations } from "next-intl";

export const amenityIconMap: Record<string, React.ElementType> = {
  "wireless internet": Wifi,
  "wine glasses": Martini,
  stove: BrickWallFire,
  hangers: Shirt,
  essentials: Gift,
  tv: Tv,
  "indoor fireplace": Flame,
  "private entrance": DoorOpen,
  "bed linens": BedDouble,
  "hair dryer": Wind,
  washer: WashingMachine,
  "air conditioning": Snowflake,
  heating: Thermometer,
  kitchen: ChefHat,
  "laptop friendly workspace": Laptop,
  "coffee maker": Coffee,
  refrigerator: Refrigerator,
  "cooking basics": CookingPot,
  "dishes and silverware": Utensils,
  microwave: Microwave,
  "free parking on premises": Car,
  "ev charger": BatteryCharging,
  gym: Dumbbell,
  pool: Waves,
  "hot tub": Bubbles,
  "patio or balcony": Landmark,
  "garden or backyard": Leaf,
  breakfast: Croissant,
  "beach essentials": Umbrella,
  crib: Baby,
  "game console": Gamepad2,
  "high chair": Baby,
  "fire extinguisher": Shield,
  "first aid kit": BriefcaseMedical,
  "smoke detector": AlarmSmoke,
  "carbon monoxide detector": AlarmSmoke,
  shampoo: SoapDispenserDroplet,
  "shower gel": SoapDispenserDroplet,
  conditioner: SoapDispenserDroplet,
  "body soap": SoapDispenserDroplet,
  "cleaning products": BrushCleaning,
  toiletries: Hand,
  bathtub: Bath,
  shower: ShowerHead,
  books: BookOpen,
  "board games": Dice6,
  "foosball table": Gamepad2,
  "arcade games": Joystick,
  "movie theater": Clapperboard,
  piano: Piano,
  "record player": Disc3,
  spa: Bubbles,
  sauna: Flame,
  "wheelchair access": Accessibility,
  elevator: ArrowUpDown,
  "security camera at entrance": Camera,
  lockbox: Lock,
  smartlock: Key,
  keypad: KeySquare,
  bike: Bike,
  boat: Sailboat,
  skiing: CableCar,
  golf: LandPlot,
  volleyball: Volleyball,
  "climbing wall": Mountain,
};

export const Amenitie = ({ amenitie }: { amenitie: { name: string } }) => {
  const Icon = amenityIconMap[amenitie.name.toLowerCase()];
  const t = useTranslations("amenities");
  return (
    <Card className="px-2 py-1 col-span-1 flex flex-row gap-1 justify-start items-center w-full">
      {Icon && <Icon className="w-5 h-5" />}
      <p className="truncate">
        {t(amenitie.name[0].toUpperCase() + amenitie.name.substr(1))}
        {/*amenitie.name[0].toUpperCase() + amenitie.name.substr(1).toLowerCase()*/}
      </p>
    </Card>
  );
};
