import { z } from "zod"

export const FullListingSchema = z.object({
    env: z.string(),
    success: z.boolean(),
    listing: z.object({
        id: z.number(),
        fs_integration_type: z.number(),
        target_id: z.number(),
        currency: z.string(),
        channel_listing_id: z.number(),
        channel_listing_status: z.null(),
        listing_group_id: z.null(),
        group_deposit: z.null(),
        room_type: z.number(),
        listing_type: z.number(),
        instant_booking_old: z.null(),
        instant_booking: z.string(),
        name: z.string(),
        nickname: z.string(),
        security_deposit: z.number(),
        cleaning_fee: z.number(),
        extra_person: z.number(),
        extra_person_type: z.string(),
        guests_included: z.number(),
        pricing_model: z.string(),
        default_daily_price: z.number(),
        weekend_price: z.null(),
        weekly_price_factor: z.null(),
        monthly_price_factor: z.null(),
        non_refundable_factor: z.number(),
        early_bird_days: z.number(),
        early_bird_percent: z.number(),
        last_minute_days: z.number(),
        last_minute_percent: z.number(),
        min_nights: z.number(),
        max_nights: z.number(),
        checkin_start: z.string(),
        checkin_end: z.string(),
        checkout: z.string(),
        cancel_policy: z.number(),
        price_tip: z.null(),
        weekly_tip: z.null(),
        monthly_tip: z.null(),
        max_notice_days: z.number(),
        min_notice_hours: z.number(),
        tags: z.array(z.unknown()),
        thumbnail_file: z.string(),
        updated_at: z.string(),
        is_listed: z.number(),
        country: z.string(),
        countrycode: z.string(),
        state: z.string(),
        city: z.string(),
        city_id: z.number(),
        zipcode: z.string(),
        street: z.string(),
        address: z.string(),
        unit: z.string(),
        neighbourhood: z.string(),
        lat: z.number(),
        lng: z.number(),
        timezone_offset: z.null(),
        timezone: z.string(),
        price_markup: z.number(),
        bottom_price: z.null(),
        owner_revenue_formula: z.null(),
        net_revenue_formula: z.null(),
        channel_commission_formula: z.null(),
        total_price_formula: z.null(),
        tax_formula: z.null(),
        cleaning_fee_formula: z.null(),
        city_tax_formula: z.null(),
        master_calendar: z.number(),
        is_cohost: z.number(),
        is_host_active: z.number(),
        children_allowed: z.number(),
        infants_allowed: z.number(),
        pets_allowed: z.number(),
        smoking_allowed: z.number(),
        events_allowed: z.number(),
        no_checkin_days: z.number(),
        no_checkout_days: z.number(),
        children_age_min: z.null(),
        children_age_max: z.number(),
        children_count_max: z.null(),
        quiet_hours: z.number(),
        quiet_hours_from: z.string(),
        quiet_hours_to: z.string(),
        pets_deposit: z.null(),
        pets_fee: z.null(),
        is_leading_listing: z.null(),
        is_completed: z.number(),
        show_airbnb_limitations: z.number(),
        inherit_parent_property: z.number(),
        owner_id: z.null(),
        nights_limit: z.number(),
        tax: z.number(),
        is_breezeway_connected: z.null(),
        listing_status: z.string(),
        property_type_id: z.number(),
        children_not_allowed_details: z.string(),
        permit_or_tax_id: z.string(),
        accounting_module: z.number(),
        use_discounts: z.number(),
        airbnb_standard_fees_enabled: z.number(),
        airbnb_occupancy_taxes_enabled: z.number(),
        airbnb_terms_for_adding_taxes_confirmed: z.number(),
        business_tax_id: z.null(),
        tot_registration_id: z.null(),
        pass_through_taxes_collection_type: z.string(),
        eligible_for_pass_through_taxes: z.number(),
        virtual_tour: z.null(),
        police_hotel_code: z.null(),
        police_hotel_name: z.null(),
        is_multi_unit_virtual: z.null(),
        allow_rtb_above_max_nights: z.null(),
        requires_stairs: z.number(),
        requires_stairs_description: z.string(),
        potential_noise: z.number(),
        potential_noise_description: z.string(),
        instant_book_welcome_message: z.string(),
        check_in_option_category: z.string(),
        check_in_option_description: z.string(),
        guest_guide: z.null(),
        access_codes: z.null(),
        payment_processors: z.string(),
        revyoos_widget_id: z.null(),
        new_listing_promotion: z.number(),
        calendar_service: z.number(),
        service_pms: z.number(),
        soft_deleted: z.number(),
        service_communication: z.number(),
        service_pms_background: z.null(),
        revenue_target: z.number(),
        high_season_rate: z.number(),
        low_season_rate: z.number(),
        lowest_rate: z.number(),
        back_to_back: z.number(),
        guests_wo_reviews: z.number(),
        guests_unverified: z.number(),
        guest_explaination: z.number(),
        guest_house_rules: z.number(),
        guests_young: z.number(),
        booking_last_minute: z.number(),
        booking_future_period: z.string(),
        hesitate: z.number(),
        booking_additional: z.string(),
        communication_sla: z.number(),
        communication_whitelabel: z.number(),
        communication_phone: z.number(),
        checkin_type: z.number(),
        lockbox_code: z.null(),
        post_cleaning: z.number(),
        post_maintenance: z.number(),
        main_contact_email: z.string(),
        main_contact_phone: z.number(),
        main_contact: z.string(),
        emergency_contact: z.string(),
        checkin_contact: z.null(),
        cleaning_contact: z.null(),
        maintenance_contact: z.null(),
        integration_nickname: z.string(),
        integration_id: z.number(),
        integration_status: z.string(),
        integration_status_cracked: z.null(),
        is_airbnb_official: z.number(),
        integration_read_only: z.number(),
        is_airbnb_cracked: z.number(),
        use_queues: z.number(),
        sync_prices: z.null(),
        sync_photos: z.null(),
        sync_rooms: z.null(),
        sync_amenities: z.null(),
        sync_description: z.null(),
        sync_settings: z.null(),
        sync_address: z.null(),
        sync_seasonal_promotions: z.null(),
        person_capacity: z.number(),
        bedrooms: z.number(),
        bathrooms: z.number(),
        bathroom_shared: z.number(),
        area: z.null(),
        beds: z.number(),
        floor: z.number(),
        customer_name: z.string(),
        customer_accounting_module: z.number(),
        meta_listing: z.null(),
        is_unit_pricing_different: z.null(),
        revenue_target_1: z.number(),
        revenue_target_2: z.number(),
        revenue_target_3: z.number(),
        revenue_target_4: z.number(),
        revenue_target_5: z.number(),
        revenue_target_6: z.number(),
        revenue_target_7: z.number(),
        revenue_target_8: z.number(),
        revenue_target_9: z.number(),
        revenue_target_10: z.number(),
        revenue_target_11: z.number(),
        revenue_target_12: z.number(),
        custom_fields: z.array(z.unknown()),
        users: z.array(
            z.object({
                id: z.number(),
                username: z.string(),
                first_name: z.string(),
                last_name: z.string(),
                phone: z.number(),
                roles: z.string()
            })
        ),
        airbnb_link: z.string(),
        parent_listing_id: z.null(),
        customer_id: z.number(),
        sync_category: z.string(),
        ical: z.string()
    }),
    host: z.object({
        nickname: z.string(),
        picture: z.string(),
        id: z.number(),
        user: z.string(),
        first_name: z.string(),
        last_name: z.string(),
        full_name: z.string()
    }),
    photos: z.array(
        z.object({
            id: z.number(),
            fs_integration_id: z.number(),
            fs_integration_type: z.number(),
            target_id: z.number(),
            listing_id: z.number(),
            id_property_rooms: z.number(),
            img_type: z.string(),
            description: z.null(),
            download: z.null(),
            has_thumb: z.number(),
            thumbnail_file: z.string(),
            original_file: z.string(),
            sort_order: z.number()
        })
    ),
    rooms: z.array(
        z.union([
            z.object({
                id: z.number(),
                name: z.string(),
                person_capacity: z.number(),
                room_type: z.string(),
                shared: z.number(),
                beds: z.array(z.object({ count: z.number(), type: z.string() }))
            }),
            z.object({
                id: z.number(),
                name: z.string(),
                person_capacity: z.number(),
                room_type: z.string(),
                shared: z.number()
            })
        ])
    ),
    amenities: z.array(
        z.union([
            z.object({
                id: z.number(),
                target_id: z.number(),
                name: z.string(),
                description: z.string(),
                json: z.string()
            }),
            z.object({
                id: z.number(),
                target_id: z.number(),
                name: z.string(),
                description: z.null(),
                json: z.string()
            }),
            z.object({
                id: z.number(),
                target_id: z.number(),
                name: z.string(),
                description: z.null(),
                json: z.null()
            })
        ])
    ),
    description: z.object({
        _id: z.number(),
        fs_listing_id: z.number(),
        lang: z.string(),
        name: z.string(),
        access: z.string(),
        arrival_info: z.null(),
        checkin_place: z.null(),
        description: z.string(),
        directions: z.string(),
        house_manual: z.null(),
        house_rules: z.string(),
        host_interaction: z.null(),
        interaction: z.null(),
        landlord_email: z.null(),
        landlord_name: z.null(),
        landlord_phone: z.null(),
        neighborhood_overview: z.string(),
        notes: z.string(),
        payment_details: z.null(),
        pickup_service: z.null(),
        space: z.string(),
        summary: z.string(),
        transit: z.null()
    }),
    details: z.object({
        _id: z.number(),
        fs_listing_id: z.number(),
        person_capacity: z.number(),
        bathrooms: z.number(),
        bathroom_shared: z.number(),
        bedrooms: z.number(),
        beds: z.number(),
        floor: z.number(),
        area: z.null(),
        wireless_type: z.null(),
        wireless_ssid: z.string(),
        wireless_password: z.string()
    }),
    reviews: z.array(
        z.object({
            name: z.string(),
            guest_picture: z.string(),
            created: z.string(),
            comments: z.string(),
            rating: z.number()
        })
    ),
    rating: z.object({
        reviews: z.number(),
        rating: z.number(),
        accuracy_rating: z.number(),
        checkin_rating: z.number(),
        clean_rating: z.number(),
        communication_rating: z.number(),
        location_rating: z.number(),
        value_rating: z.number()
    }),
    calendar: z.array(z.object({ start: z.string(), end: z.string() })),
    price: z.number(),
    currency_data: z.object({
        iso_code: z.string(),
        unicode: z.string(),
        symbol: z.string(),
        position: z.string()
    }),
    custom_stay: z.array(
        z.object({
            id: z.number(),
            fs_listing_id: z.number(),
            date_start: z.string(),
            date_end: z.string(),
            checkin_weekday: z.null(),
            min_stay: z.number()
        })
    ),
    min_prices: z.object({
        min_price: z.number(),
        min_price_monthly: z.number(),
        available_from: z.string()
    })
});

export type FullListingType = z.infer<typeof FullListingSchema>;